spring.application.name=brekfood

# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# --- CORS ---
brekfood.cors.allowed-origins=http://localhost:3000
