-- =============================================================================
-- BrekFood — Phase 1: Identity Context
-- Migration : V1__create_users_table.sql
-- Description: Creates the users table for the authentication &
--              identity bounded context.
-- =============================================================================
CREATE TABLE IF NOT EXISTS users
(
    id            UUID                     NOT NULL DEFAULT gen_random_uuid(),
    email         VARCHAR(255)             NOT NULL,
    password_hash VARCHAR(255)             NOT NULL,
    name          VARCHAR(100)             NOT NULL,
    role          VARCHAR(50)              NOT NULL,
    active        BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('CUSTOMER', 'RESTAURANT_OWNER', 'DRIVER', 'ADMIN'))
);
-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_email  ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role   ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_active ON users (active);
-- Table/column comments
COMMENT ON TABLE  users               IS 'Platform users — all roles (CUSTOMER, RESTAURANT_OWNER, DRIVER, ADMIN)';
COMMENT ON COLUMN users.id            IS 'UUID primary key — generated by gen_random_uuid()';
COMMENT ON COLUMN users.email         IS 'Unique lower-cased e-mail — used as login username';
COMMENT ON COLUMN users.password_hash IS 'BCrypt hash of user password — never plain-text';
COMMENT ON COLUMN users.name          IS 'User display name — max 100 characters';
COMMENT ON COLUMN users.role          IS 'Platform role: CUSTOMER | RESTAURANT_OWNER | DRIVER | ADMIN';
COMMENT ON COLUMN users.active        IS 'Soft-delete flag — false means deactivated/banned';
COMMENT ON COLUMN users.created_at    IS 'UTC timestamp of creation (JPA auditing)';
COMMENT ON COLUMN users.updated_at    IS 'UTC timestamp of last update (JPA auditing)';
